#!/bin/sh

case "$1" in
    start)
        echo "Starting sshd..."
        if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
            ssh-keygen -A
        fi
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
        /usr/sbin/sshd
        ;;
    stop)
        echo "Stopping sshd..."
        killall sshd
        ;;
esac
